export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_SEND_OTP = 'USER_SEND_OTP'
export const USER_SEND_OTP_SUCCESS = 'USER_SEND_OTP_SUCCESS'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT ='USER_LOGOUT'

